### ISSUE TITLE
Program to implement Circular Queue

### ISSUE THREAD

**Issue by mrsamirr** [Coderich-Community/Hacktoberfest-2023#21]

**Comment by indrajeet2000** [comment]
Hi could you assign me this issue

**Comment by FarazRashid** [comment]
Hi could you assign me this issue? I have experience in data structures and working in c++!

**Comment by TanushreeBorase** [comment]
This is my first hand at open source contribution, I would like to take this issue and contribute my code in C++.Can you assign me this issue?

**Comment by mrsamirr** [comment]
> This is my first hand at open source contribution, I would like to take this issue and contribute my code in C++.Can you assign me this issue?

Oh! Great @TanushreeBorase 
But @FarazRashid says first 
so he will assigned first
U can checkout other open issues.
