### ISSUE TITLE
Reverse Linked List In C++

### ISSUE THREAD

**Issue by mrsamirr** [Coderich-Community/Hacktoberfest-2023#5]
Submit your Algorithm in C/C++

**Comment by vivekpanjwani** [comment]
Assign me please

**Comment by indrajeet2000** [comment]
Hi could you assign me this issue

**Comment by vivekpanjwani** [comment]
Hello mrsamirr I submitted the program

**Comment by i-OmSharma** [comment]
@mrsamirr Assign this to me

**Comment by hydraveer** [comment]
@mrsamirr assign this to me

**Comment by Selenophile-ishan** [comment]
new to this, I can do this, can someone assign me?

**Comment by mrsamirr** [comment]
Yes @Selenophile-ishan go ahead!

**Comment by mrsamirr** [comment]
Already Completed! @everyone
So i close this issue  ,Now
