### ISSUE TITLE
Find Minimum Index of Repeating Element in an Array

### ISSUE THREAD

**Issue by mrsamirr** [Coderich-Community/Hacktoberfest-2023#69]
Implement Your Algorithm in any language

**Comment by ankur-dahiya** [comment]
@mrsamirr please assign this to me

**Comment by ankur-dahiya** [comment]
please merge with appropriate tags

**Comment by mrsamirr** [comment]
No need to worry @ankur-dahiya 
All PR are accepted under `hacktoberfest- accepted` Label
